/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban.View.HomePage;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlydatban.Model.Booking;
import quanlydatban.Model.Customer;
import quanlydatban.Model.Table;
import quanlydatban.Service.BookingService;
import quanlydatban.Service.CustomerService;
import java.text.SimpleDateFormat;

/**
 *
 * @author HELLO
 */
public class pnScreenDanhSach extends javax.swing.JPanel implements TableUpdateListener {

    private TableUpdateListener datbanmoiListener;
    BookingService bks = new BookingService();
    CustomerService cus = new CustomerService();

    /**
     * Creates new form pnScreenDanhSach
     */
    public pnScreenDanhSach() {
        initComponents();
        setCount();
        ViewTable();
    }

    private void ViewTable() {
        DefaultTableModel model = (DefaultTableModel) tbMain.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        List<Booking> list = bks.getAllBooking();

        // TẠO BỘ ĐỊNH DẠNG GIỜ:PHÚT
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");

        for (Booking b : list) {
            String timeStartStr = "";
            String timeEndStr = "";

            // Kiểm tra null để tránh lỗi (quan trọng với Timestamp)
            if (b.getTimeStart() != null) {
                timeStartStr = sdf.format(b.getTimeStart());
            }
            if (b.getTimeEnd() != null) {
                timeEndStr = sdf.format(b.getTimeEnd());
            }

            // Tạo chuỗi hiển thị gộp 
            String timeDisplay = timeStartStr + " - " + timeEndStr;

            // Đổ dữ liệu vào hàng 
            model.addRow(new Object[]{
                b.getIdBooking(), // Cột 0: Mã đặt bàn
                b.getListTables(), // Cột 1: Bàn
                cus.getCus(b.getIDcus()).getNameCus(),// Cột 2: Khách hàng
                cus.getCus(b.getIDcus()).getCusPhone(),// Cột 3: Điện thoại
                timeDisplay, // Cột 4: Thời Gian Dùng
                b.getGuestCount(), // Cột 5: Số khách
                b.getNote(), // Cột 6: Ghi chú
                b.getIsComplete() // Cột 7: Trạng thái 
            });
        }
    }

    private void setCount() {
        this.txtTongBooking.setText("" + bks.getCountBooking());
        this.txtCountComplete.setText("" + bks.getCount("Hoàn Thành"));
        this.txtCountCancel.setText("" + bks.getCount("Đã Hủy"));

    }

    private void CompleteSelectedBooking(int selectedRowIndex, int idBooking) {
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Xác nhận hoàn thành đơn " + idBooking,
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            if (bks.setIsComplete(idBooking)) {
                ViewTable();

                JOptionPane.showMessageDialog(this, "Đã xác nhận hoàn thành đơn " + idBooking);
                setCount();
            }
        }
    }

    private void CancelSelectedBooking(int selectedRowIndex, int idBooking) {
        DefaultTableModel model = (DefaultTableModel) tbMain.getModel();

        // Xác nhận hủy
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn hủy đặt bàn ID: " + idBooking,
                "Xác nhận hủy",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (bks.CancelBooking(idBooking)) {
                    ViewTable();

                    JOptionPane.showMessageDialog(this,
                            "Đơn đặt bàn ID " + idBooking + " đã được chuyển trạng thái: Đã Hủy",
                            "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);

                    setCount();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật trạng thái đơn.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenDanhSach = new javax.swing.JPanel();
        pnTitle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        thongkedatban = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTongBooking = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCountComplete = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCountCancel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(870, 500));
        setLayout(new java.awt.BorderLayout());

        screenDanhSach.setLayout(new java.awt.BorderLayout());

        pnTitle.setBackground(new java.awt.Color(255, 204, 204));
        pnTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTitle.setPreferredSize(new java.awt.Dimension(870, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Danh sách đặt bàn");

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTitleLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(328, 328, 328))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        screenDanhSach.add(pnTitle, java.awt.BorderLayout.PAGE_START);

        main.setLayout(new java.awt.BorderLayout());

        thongkedatban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tổng số bàn đã đặt");

        txtTongBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongBooking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongBooking.setBorder(null);
        txtTongBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txtTongBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jLabel7.setText("Thống kê đặt bàn");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(349, 74));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hoàn thành");

        txtCountComplete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountComplete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountComplete.setBorder(null);
        txtCountComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txtCountComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hủy bỏ");

        txtCountCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountCancel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountCancel.setBorder(null);
        txtCountCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCountCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout thongkedatbanLayout = new javax.swing.GroupLayout(thongkedatban);
        thongkedatban.setLayout(thongkedatbanLayout);
        thongkedatbanLayout.setHorizontalGroup(
            thongkedatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongkedatbanLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(thongkedatbanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thongkedatbanLayout.setVerticalGroup(
            thongkedatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongkedatbanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(thongkedatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        main.add(thongkedatban, java.awt.BorderLayout.PAGE_START);

        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đặt bàn", "Bàn", "Khách hàng", "Điện thoại", "Thời Gian Dùng", "Số khách", "Ghi chú", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMain.setMaximumSize(new java.awt.Dimension(2147483647, 0));
        tbMain.setPreferredSize(new java.awt.Dimension(700, 1000));
        tbMain.setRowHeight(40);
        tbMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbMainKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbMain);
        if (tbMain.getColumnModel().getColumnCount() > 0) {
            tbMain.getColumnModel().getColumn(0).setResizable(false);
            tbMain.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbMain.getColumnModel().getColumn(1).setResizable(false);
            tbMain.getColumnModel().getColumn(1).setPreferredWidth(40);
            tbMain.getColumnModel().getColumn(2).setResizable(false);
            tbMain.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbMain.getColumnModel().getColumn(3).setResizable(false);
            tbMain.getColumnModel().getColumn(3).setPreferredWidth(90);
            tbMain.getColumnModel().getColumn(4).setResizable(false);
            tbMain.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbMain.getColumnModel().getColumn(5).setResizable(false);
            tbMain.getColumnModel().getColumn(5).setPreferredWidth(30);
            tbMain.getColumnModel().getColumn(6).setResizable(false);
            tbMain.getColumnModel().getColumn(6).setPreferredWidth(150);
            tbMain.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setText("Danh sách đặt bàn");

        jButton1.setBackground(new java.awt.Color(237, 233, 216));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Hoàn thành");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(128, 128, 128))));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(237, 233, 216));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Hủy đơn");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(128, 128, 128))));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        main.add(jPanel3, java.awt.BorderLayout.CENTER);

        screenDanhSach.add(main, java.awt.BorderLayout.CENTER);

        add(screenDanhSach, java.awt.BorderLayout.CENTER);
        screenDanhSach.getAccessibleContext().setAccessibleName("pnScreenDanhSach");
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongBookingActionPerformed

    private void txtCountCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountCompleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountCompleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n = this.tbMain.getSelectedRow();
        int id = (int) this.tbMain.getValueAt(n, 0);
        CompleteSelectedBooking(n, id);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int n = this.tbMain.getSelectedRow();
        int id = (int) this.tbMain.getValueAt(n, 0);
        CancelSelectedBooking(n, id);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbMainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMainKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMainKeyPressed

    private void txtCountCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountCancelActionPerformed
//    public void setDatbanmoiListener(TableUpdateListener listener) {
//        this.datbanmoiListener = listener;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JPanel screenDanhSach;
    private javax.swing.JTable tbMain;
    private javax.swing.JPanel thongkedatban;
    private javax.swing.JTextField txtCountCancel;
    private javax.swing.JTextField txtCountComplete;
    private javax.swing.JTextField txtTongBooking;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onTableStatusUpdated() {

        ViewTable();
        if (datbanmoiListener != null) {
            this.datbanmoiListener.onTableStatusUpdated();
        }
        setCount();
        this.tbMain.revalidate();
        this.tbMain.repaint();
    }
}
