/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban.View.HomePage;

import java.awt.Color; // Cần thêm dòng này nếu chưa có
import java.awt.event.FocusAdapter; // Cần thêm dòng này nếu chưa có
import java.awt.event.FocusEvent; // Cần thêm dòng này nếu chưa có
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import quanlydatban.Model.Booking; // Sử dụng Model Booking duy nhất
import quanlydatban.Service.BookingService; // Gọi thông qua Service thay vì DAO trực tiếp

/**
 *
 * @author Admin
 */
public class pnScreenTimKiem extends javax.swing.JPanel {

    private final String PLACEHOLDER_TEXT = "Tìm kiếm theo tên hoặc số điện thoại";

    private BookingService bookingService;
    private DefaultTableModel tableModel;

    /**
     * Creates new form pnScreenTimKiem
     */
    public pnScreenTimKiem() {
        initComponents();

        bookingService = new BookingService();

        initComponents();
        addPlaceholderFeature(jTextField2);

        // Gọi khởi tạo bảng (chỉ khởi tạo model, không tải dữ liệu)
        khoiTaoJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(870, 446));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm đặt bàn");
        jLabel1.setMaximumSize(new java.awt.Dimension(129, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(129, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(231, 227, 220));

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Tìm kiếm theo tên hoặc số điện thoại");
        jTextField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(128, 128, 128))));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 179, 190));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(245, 17, 53))));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Screenshot 2025-12-15 113641.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(51, 51, 255))));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đặt bàn", "Bàn", "Khách hàng", "Điện thoại", "Thời gian dùng", "Số khách", "Ghi chú", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:                                     
        jButton2ActionPerformed(evt); // Nhấn Enter cũng sẽ kích hoạt tìm kiếm
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField2.setText(PLACEHOLDER_TEXT);
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.requestFocus();

        // Làm trống bảng
        if (tableModel != null) {
            tableModel.setRowCount(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String tuKhoa = jTextField2.getText().trim();

        // Nếu để trống hoặc là placeholder, lấy toàn bộ danh sách chi tiết từ Service
        if (tuKhoa.isEmpty() || tuKhoa.equals(PLACEHOLDER_TEXT)) {
            taiDuLieuLenBang(bookingService.getAllBooking());
            return;
        }

        // Gọi Service thực hiện tìm kiếm (Service sẽ JOIN SQL lấy đủ thông tin)
        List<Booking> ketQua = bookingService.searchBooking(tuKhoa);

        // Hiển thị kết quả
        taiDuLieuLenBang(ketQua);

        if (ketQua.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy đặt bàn nào khớp với: " + tuKhoa,
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // >>> Vị trí DÁN CODE 3: Thêm phương thức xử lý FocusListener <<<
    private void addPlaceholderFeature(JTextField textField) {
        textField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(PLACEHOLDER_TEXT)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(PLACEHOLDER_TEXT);
                    textField.setForeground(new java.awt.Color(204, 204, 204));
                }
            }
        });
    }

    // --- PHƯƠNG THỨC KHỞI TẠO BẢNG VÀ TẢI DỮ LIỆU BAN ĐẦU ---
    private void khoiTaoJTable() {
        tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0); // Bảng trống khi khởi tạo
    }

// --- PHƯƠNG THỨC ĐỔ DỮ LIỆU VÀO BẢNG ---
    private void taiDuLieuLenBang(List<Booking> listBooking) {
        tableModel.setRowCount(0);
        if (listBooking != null) {
            for (Booking b : listBooking) {
                tableModel.addRow(new Object[]{
                    b.getIdBooking(), // 1. Mã đặt bàn
                    b.getListTables(), // 2. Bàn
                    b.getNameCus(), // 3. Khách hàng
                    b.getCusPhone(), // 4. Điện thoại
                    b.getTimeRangeDisplay(), // 5. Thời gian (HH:mm - HH:mm)
                    b.getGuestCount(), // 6. Số khách
                    b.getNote(), // 7. Ghi chú
                    b.getIsComplete() // 8. Trạng thái
                });
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
