/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban.View.HomePage;
import java.awt.Color; // Cần thêm dòng này nếu chưa có
import java.awt.event.FocusAdapter; // Cần thêm dòng này nếu chưa có
import java.awt.event.FocusEvent; // Cần thêm dòng này nếu chưa có
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import quanlydatban.Model.BookingDetail; // Thêm Model Detail
import quanlydatban.Dao.BookingDao; // Thêm DAO
/**
 *
 * @author Admin
 */
public class pnScreenTimKiem extends javax.swing.JPanel {
    private final String PLACEHOLDER_TEXT = "Tìm kiếm theo tên hoặc số điện thoại";
    
    private BookingDao bookingDao;
    private DefaultTableModel tableModel;
    /**
     * Creates new form pnScreenTimKiem
     */
    public pnScreenTimKiem() {
        initComponents();
        addPlaceholderFeature(jTextField2);
        
       bookingDao = new BookingDao(); 
    
    initComponents();
    addPlaceholderFeature(jTextField2);
    
    // Gọi khởi tạo bảng (chỉ khởi tạo model, không tải dữ liệu)
    khoiTaoJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(870, 446));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm đặt bàn");
        jLabel1.setMaximumSize(new java.awt.Dimension(129, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(129, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(231, 227, 220));

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Tìm kiếm theo tên hoặc số điện thoại");
        jTextField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(128, 128, 128))));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 179, 190));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(245, 17, 53))));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Screenshot 2025-12-15 113641.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(51, 51, 255))));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đặt bàn", "Bàn", "Khách hàng", "Điện thoại", "Thời gian dùng", "Số khách", "Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // Đặt lại ô tìm kiếm về trạng thái placeholder
    jTextField2.setText(PLACEHOLDER_TEXT);
    jTextField2.setForeground(new java.awt.Color(204, 204, 204));
    jTextField2.requestFocus();
    
    // >>> THAY ĐỔI: CHỈ LÀM TRỐNG BẢNG, KHÔNG TẢI LẠI DỮ LIỆU <<<
    if (tableModel != null) {
        tableModel.setRowCount(0);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String tuKhoa = jTextField2.getText().trim();
    
    if (tuKhoa.isEmpty() || tuKhoa.equals(PLACEHOLDER_TEXT)) {
        // Nếu trống, hiển thị lại toàn bộ dữ liệu
        taiDuLieuLenBang(bookingDao.getAllBookingDetail()); 
        return;
    }
    
    // Gọi DAO để tìm kiếm
    List<BookingDetail> ketQua = bookingDao.searchBookingDetail(tuKhoa);
    
    // Đổ dữ liệu kết quả tìm kiếm vào JTable
    taiDuLieuLenBang(ketQua);
    
    if (ketQua.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy đặt bàn nào khớp với từ khóa: " + tuKhoa, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // >>> Vị trí DÁN CODE 3: Thêm phương thức xử lý FocusListener <<<
    private void addPlaceholderFeature(JTextField textField) {
        // Lấy lại giá trị Text và Color đã được set sẵn từ initComponents()
        
        textField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                // Khi click vào: Nếu text là Placeholder, thì xóa text và đổi màu
                if (textField.getText().equals(PLACEHOLDER_TEXT)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK); // Đổi màu về màu chữ thường
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Khi mất focus: Nếu text trống, thì hiện lại Placeholder và đổi màu
                if (textField.getText().isEmpty()) {
                    textField.setText(PLACEHOLDER_TEXT);
                    textField.setForeground(new java.awt.Color(204, 204, 204)); // Dùng lại màu đã set trong initComponents
                }
            }
        });
    }

    // --- PHƯƠNG THỨC KHỞI TẠO BẢNG VÀ TẢI DỮ LIỆU BAN ĐẦU ---
private void khoiTaoJTable() {
    tableModel = (DefaultTableModel) jTable1.getModel();
    
    // XÓA DÒNG NÀY: taiDuLieuLenBang(bookingDao.getAllBookingDetail()); 
    
    // Nếu bạn muốn bảng trống trơn khi khởi động:
    tableModel.setRowCount(0);
}

// --- PHƯƠNG THỨC ĐỔ DỮ LIỆU VÀO BẢNG ---
private void taiDuLieuLenBang(List<BookingDetail> listBookingDetail) {
    tableModel.setRowCount(0); 
    if (listBookingDetail != null) {
        for (BookingDetail detail : listBookingDetail) {
            // ...
            tableModel.addRow(new Object[]{
                detail.getIdBooking(),
                detail.getIdTable(),     
                detail.getNameCus(),     
                detail.getCusPhone(),    
                detail.getDurationString(), // <<< THAY THẾ BẰNG DURATION
                detail.getGuestCount(),  
                detail.getNote()         
            });
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
